PS\Bundle\BalanceBudgetBundle\Entity\FooterMenu:
    type: entity
    repositoryClass: PS\Bundle\BalanceBudgetBundle\Repository\FooterMenuRepository
    table: ps_footer_menu
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 255
        url_type:
            type: string
            length: 255
        url:
            type: string
            length: 255
        target:
            type: string
            length: 255
