PS\Bundle\BalanceBudgetBundle\Entity\Issue:
    type: entity
    repositoryClass: PS\Bundle\BalanceBudgetBundle\Repository\IssueRepository
    table: ps_issue
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        title:
            type: string
            length: 255  
        lead:
            type: text
        description:
            type: text
        option_values:
            type: text 
        is_parent:
            type: boolean
            default: false
        is_reduceBy:
            type: boolean
            default: false  
        is_cumulative:
            type: boolean
            default: false    
        is_active:
            type: boolean
            default: true
        created_at:
            type: datetime
    oneToMany:
        children:
          targetEntity: Issue
          mappedBy: parent        
    manyToOne:
        parent:
            targetEntity: Issue
            inversedBy: children
        controltype:
            targetEntity: ControlType
            joinColumn:
                name: control_type_id
                referencedColumnName: id
        sectionissue:
            targetEntity: Section
            joinColumn:
                name: section_id
                referencedColumnName: id
        dependency:
            targetEntity: Dependency
            joinColumn:
                name: dependency_id
                referencedColumnName: id   
        issuegroup:
            targetEntity: IssueGroup
            joinColumn:
                name: issuegroup_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [  setCreatedAtValue]
       
