PS\Bundle\BalanceBudgetBundle\Entity\SpendingCategory:
    type: entity
    repositoryClass: PS\Bundle\BalanceBudgetBundle\Repository\SpendingCategoryRepository
    table: ps_spending_category
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        title:
            type: string
            length: 255    
        description:
            type: text
        is_active:
            type: boolean
            default: true
    oneToMany:
        sections:
            targetEntity: SpendingSection
            mappedBy: category

        
    
