PS\Bundle\BalanceBudgetBundle\Entity\SpendingIssue:
    type: entity
    repositoryClass: PS\Bundle\BalanceBudgetBundle\Repository\SpendingIssueRepository
    table: ps_issue
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        section:
            type: string
            length: 255
        category:
            type: string
            length: 255
        name:
            type: string
            length: 255
        description:
            type: text
            length: 255
        option_values:
            type: text
            length: 255
        created_at:
            type: datetime
    manyToOne:
        controltype:
            targetEntity: ControlType
            joinColumn:
                name: control_type_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [  setCreatedAtValue]

