PS\Bundle\BalanceBudgetBundle\Entity\WidgetType:
    type: entity
    repositoryClass: PS\Bundle\BalanceBudgetBundle\Repository\WidgetTypeRepository
    table: widgettype
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        properties:
            type: array
            
        
        
