PS\Bundle\SunshineBundle\Entity\IssueTypeProperties:
    type: entity
    repositoryClass: PS\Bundle\SunshineBundle\Repository\IssueTypePropertiesRepository
    table: issuetypeproperties
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        value:
            type: string
            length: 255
        is_active:
            type: boolean
            nullable: true
        created_at:
            type: datetime
        updated_at:
            type: datetime
            nullable: true
    manyToOne:
        issuetype:
            targetEntity: IssueType
            inversedBy: properties
            joinColumn:
                name: property_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [  setCreatedAtValue]
        preUpdate: [ setUpdatedAtValue ]
        