planner:
    pattern:  /planner/{id}
    defaults: { _controller: "PSBalanceBudgetBundle:Budget:index" }
    
process_issue:
    pattern: /processissue
    defaults: { _controller: "PSBalanceBudgetBundle:Budget:processIssue" }

update_debt:
    pattern: /updatedebt
    defaults: { _controller: "PSBalanceBudgetBundle:Budget:updateDebt" }

ckeditorsave:
    pattern:  /ckeditorsave
    defaults: { _controller: "PSBalanceBudgetBundle:Default:CKEditorSave" }

postcode:
    pattern: /postcode
    defaults: { _controller: "PSBalanceBudgetBundle:Default:plannerPostcode" }

postcode_update:
    pattern: /update_postcode
    defaults: { _controller: "PSBalanceBudgetBundle:Default:updatePostcode" }

offline_submission:
    pattern: /offlinesubmission
    defaults: { _controller: "PSBalanceBudgetBundle:Default:offlineSubmission" }

registration:
    pattern: /registration
    defaults: { _controller: "PSBalanceBudgetBundle:Registration:registration" }    
