planner:
    pattern:  /planner
    defaults: { _controller: "PSBalanceBudgetBundle:Budget:index" }
    
save_issue:
    pattern: /saveissue
    defaults: { _controller: "PSBalanceBudgetBundle:Budget:saveIssue" }


update_debt:
    pattern: /updatedebt
    defaults: { _controller: "PSBalanceBudgetBundle:Budget:updateDebt" }

ckeditorsave:
    pattern:  /ckeditorsave
    defaults: { _controller: "PSBalanceBudgetBundle:Budget:CKEditorSave" }