planner:
    pattern:  /planner/{slug}
    defaults: { _controller: "PSBalanceBudgetBundle:Budget:index" }
    
detailed_submission:
    pattern: /detailedsubmission/{slug}
    defaults: { _controller: "PSBalanceBudgetBundle:Budget:detailedSubmission" }
    
summary:
    pattern: /summary
    defaults: { _controller: "PSBalanceBudgetBundle:Budget:summary" }    
    
process_issue:
    pattern: /processissue
    defaults: { _controller: "PSBalanceBudgetBundle:Budget:processIssue" }

update_debt:
    pattern: /updatedebt
    defaults: { _controller: "PSBalanceBudgetBundle:Budget:updateDebt" }

ckeditorsave:
    pattern:  /ckeditorsave
    defaults: { _controller: "PSBalanceBudgetBundle:Default:CKEditorSave" }

postcode:
    pattern: /postcode
    defaults: { _controller: "PSBalanceBudgetBundle:Default:plannerPostcode" }

postcode_update:
    pattern: /update_postcode
    defaults: { _controller: "PSBalanceBudgetBundle:Default:updatePostcode" }

offline_submission:
    pattern: /offlinesubmission
    defaults: { _controller: "PSBalanceBudgetBundle:Default:offlineSubmission" }

registration:
    pattern: /registration
    defaults: { _controller: "PSBalanceBudgetBundle:Registration:registration" }    

header_menu:
    pattern: /dynamicheader
    defaults: { _controller: "PSBalanceBudgetBundle:Default:dynamicHeader" }

footer_menu:
    pattern: /dynamicfooter
    defaults: { _controller: "PSBalanceBudgetBundle:Default:dynamicFooter" }

spending:
    pattern: /spending
    defaults: { _controller: "PSBalanceBudgetBundle:Budget:spending" }

spending_save:
    pattern: /spendingSave
    defaults: { _controller: "PSBalanceBudgetBundle:Budget:spendingSave" }
