planner:
    pattern:  /planner
    defaults: { _controller: "PSBalanceBudgetBundle:Budget:index" }
    
process_issue:
    pattern: /processissue
    defaults: { _controller: "PSBalanceBudgetBundle:Budget:processIssue" }

update_debt:
    pattern: /updatedebt
    defaults: { _controller: "PSBalanceBudgetBundle:Budget:updateDebt" }

ckeditorsave:
    pattern:  /ckeditorsave
    defaults: { _controller: "PSBalanceBudgetBundle:Budget:CKEditorSave" }
