parameters:
#    ps_balance_budget.example.class: PS\Bundle\BalanceBudgetBundle\Example

services:
#    ps_balance_budget.example:
#        class: %ps_balance_budget.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
   

   
    

    ps_balance_budget.admin.category:
        class: PS\Bundle\BalanceBudgetBundle\Admin\CategoryAdmin
        arguments: [~, PS\Bundle\BalanceBudgetBundle\Entity\Category, PSBalanceBudgetBundle:CategoryAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Issues, label: Category}

    ps_balance_budget.admin.section:
        class: PS\Bundle\BalanceBudgetBundle\Admin\SectionAdmin
        arguments: [~, PS\Bundle\BalanceBudgetBundle\Entity\Section, PSBalanceBudgetBundle:SectionAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Issues, label: Section}

    ps_balance_budget.admin.issue:
        class: PS\Bundle\BalanceBudgetBundle\Admin\IssueAdmin
        arguments: [~, PS\Bundle\BalanceBudgetBundle\Entity\Issue, PSBalanceBudgetBundle:IssueAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Issues, label: Issue}

    ps_balance_budget.admin.control_type:
        class: PS\Bundle\BalanceBudgetBundle\Admin\ControlTypeAdmin
        arguments: [~, PS\Bundle\BalanceBudgetBundle\Entity\ControlType, PSBalanceBudgetBundle:ControlTypeAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Control Types, label: ControlType}
