parameters:
#    ps_balance_budget.example.class: PS\Bundle\BalanceBudgetBundle\Example

services:
#    ps_balance_budget.example:
#        class: %ps_balance_budget.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
