parameters:
  

services:
    visitor_tracker_service:
        class: PS\Bundle\BalanceBudgetBundle\Logic\VisitorTracker
        arguments: [@request,@doctrine.orm.entity_manager]
        scope: request
   

   
    

    ps_balance_budget.admin.category:
        class: PS\Bundle\BalanceBudgetBundle\Admin\CategoryAdmin
        arguments: [~, PS\Bundle\BalanceBudgetBundle\Entity\Category, PSBalanceBudgetBundle:CategoryAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Issues, label: Category}

    ps_balance_budget.admin.section:
        class: PS\Bundle\BalanceBudgetBundle\Admin\SectionAdmin
        arguments: [~, PS\Bundle\BalanceBudgetBundle\Entity\Section, PSBalanceBudgetBundle:SectionAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Issues, label: Section}

    ps_balance_budget.admin.issue:
        class: PS\Bundle\BalanceBudgetBundle\Admin\IssueAdmin
        arguments: [~, PS\Bundle\BalanceBudgetBundle\Entity\Issue, PSBalanceBudgetBundle:IssueAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Issues, label: Issue}

#    ps_balance_budget.admin.control_type:
#        class: PS\Bundle\BalanceBudgetBundle\Admin\ControlTypeAdmin
#        arguments: [~, PS\Bundle\BalanceBudgetBundle\Entity\ControlType, PSBalanceBudgetBundle:ControlTypeAdmin]
#        tags:
#            - {name: sonata.admin, manager_type: orm, group: Control Types, label: ControlType}

    ps_balance_budget.admin.budget_planner:
        class: PS\Bundle\BalanceBudgetBundle\Admin\BudgetPlannerAdmin
        arguments: [~, PS\Bundle\BalanceBudgetBundle\Entity\BudgetPlanner, PSBalanceBudgetBundle:BudgetPlannerAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Settings, label: Budget Planner}
