<?php

namespace PS\Bundle\BalanceBudgetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DependencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DependencyRepository extends EntityRepository
{
       
}
