<?php

namespace PS\Bundle\BalanceBudgetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueRepository extends EntityRepository
{
    public function getChildrenIds($issueId){
       
        $parentIssue = $this->findOneById($issueId);
        $children = $parentIssue->getChildren();
        $childrenIdArray = array();
        foreach($children as $child)
        {
            $childrenIdArray[] = $child->getId();
        }
     
       return $childrenIdArray; 
    }
    
    public function getSiblingIssueIds($sectionId){
        
        $siblings = $this->findBy('section_id', $sectionId);
        $siblingsArray = array();
        foreach($siblings as $sibling){
            
            $siblingsArray[] = $sibling->getId();
        }
        return $siblingsArray;
    }
}
