<?php

namespace PS\Bundle\BalanceBudgetBundle\Repository;

use Doctrine\ORM\EntityRepository;
use PS\Bundle\BalanceBudgetBundle\Entity\VisitorActivity;
/**
 * VisitorActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitorActivityRepository extends EntityRepository
{
    public function saveActivity($sessionId, $issueId, $value){
        
        $visitorActivity  = $this->findOneBy(array('session_id'=>$sessionId, 'issue_id' => $issueId));
        // update the row
        if(isset($visitorActivity))
        {
          $visitorActivity->setIssueValue($value);  
        }
        else // create the row
        {
           $visitorActivity = new VisitorActivity();
           $visitorActivity->setSessionId($sessionId);
           $visitorActivity->setIssueId($issueId);
           $visitorActivity->setIssueValue($value);
           $visitorActivity->setHasTouched(true);
        }
        
        $em = $this->getEntityManager();
        $em->persist($visitorActivity);
        $em->flush();
        
    }
    

    public function getTheSetParentValues($session_id)
    {
        $totalDebt = 0;
       $parentIssues = $this->getEntityManager()->getRepository('PSBalanceBudgetBundle:Issue')->getParentIssues(); 
        foreach($parentIssues as $parent){
           $parentIssue = $this->findOneBy(array('issue_id' => $parent->getId(), 'session_id' => $session_id));
           if(isset($parentIssue))
           {
               $totalDebt += $parentIssue->getIssueValue();
           }
           
        }
        return $totalDebt;
    }       
    
}
