<?php

namespace PS\Bundle\BalanceBudgetBundle\Repository;

use Doctrine\ORM\EntityRepository;
use PS\Bundle\BalanceBudgetBundle\Entity\VisitorSpendingActivity;

/**
 * VisitorSpendingActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitorSpendingActivityRepository extends EntityRepository
{
    public function saveActivity($sessionId, $issueId, $value=0, $percentage=0)
    {
        $em = $this->getEntityManager();

        $issue = $em->getRepository('PSBalanceBudgetBundle:SpendingIssue')->find($issueId);
        $visitorActivity  = $this->findOneBy(array('session_id'=>$sessionId, 'issue' => $issue));
        // update the row
        if(!$visitorActivity)
        {
            $visitorActivity = new VisitorSpendingActivity();
        }

        $visitorActivity->setSessionId($sessionId);
        $visitorActivity->setIssue($issue);
        $visitorActivity->setIssueValue($value);
        $visitorActivity->setHasTouched(true);
        $visitorActivity->setCreatedAt(new \DateTime());
        $visitorActivity->setIssuePercentage($percentage);


        $em->persist($visitorActivity);
        $em->flush();

    }
}
