<?php

namespace PS\Bundle\BalanceBudgetBundle\Repository;

use Doctrine\ORM\EntityRepository;
use PS\Bundle\BalanceBudgetBundle\Entity\VisitorDetailedSubmissionActivity;
/**
 * VisitorDetailedSubmissionActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitorDetailedSubmissionActivityRepository extends EntityRepository
{
    
    public function saveDetailedIssue($issueId, $issueValue, $sessionId){
        $detailedIssue = $this->findOneBy(array('session_id'=>$sessionId, 'issue_id' => $issueId));
        
        if(isset($detailedIssue))
        {
            $detailedIssue->setIssueValue($issueValue);
        }    
        else
        {    
        $detailedSubmission = new VisitorDetailedSubmissionActivity();
        $detailedSubmission->setIssueId($issueId);
        $detailedSubmission->setIssueValue($issueValue);
        $detailedSubmission->setSessionId($sessionId);
        
        }
          $em = $this->getEntityManager();
        $em->persist($visitorActivity);
        $em->flush();
        
    }
    
    
}
