issue:
    pattern:  /
    defaults: { _controller: "PSBalanceBudgetBundle:Issue:index" }

issue_show:
    pattern:  /{id}/show
    defaults: { _controller: "PSBalanceBudgetBundle:Issue:show" }

issue_new:
    pattern:  /new
    defaults: { _controller: "PSBalanceBudgetBundle:Issue:new" }

issue_create:
    pattern:  /create
    defaults: { _controller: "PSBalanceBudgetBundle:Issue:create" }
    requirements: { _method: post }

issue_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PSBalanceBudgetBundle:Issue:edit" }

issue_update:
    pattern:  /{id}/update
    defaults: { _controller: "PSBalanceBudgetBundle:Issue:update" }
    requirements: { _method: post|put }

issue_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PSBalanceBudgetBundle:Issue:delete" }
    requirements: { _method: post|delete }
